--table mahasiswa
CREATE TABLE mahasiswa(
MAHASISWAID INT PRIMARY KEY NOT NULL,
NAMA_MAHASISWA TEXT NOT NULL,
NIM TEXT NOT NULL,
JURUSANID INT NOT NULL,
ALAMAT TEXT NOT NULL
);

INSERT INTO mahasiswa(MAHASISWAID,NAMA_MAHASISWA, NIM, JURUSANID, ALAMAT) VALUES(1, 'Bimo', '000123', 2, 'Tangerang Selatan');

INSERT INTO mahasiswa(MAHASISWAID,NAMA_MAHASISWA, NIM, JURUSANID, ALAMAT) VALUES(2, 'Toni', '000125', 1, 'Jakarta');


--dosen
CREATE TABLE dosen(
DOSENID INT PRIMARY KEY NOT NULL,
NAMA_DOSEN TEXT NOT NULL
);

INSERT INTO dosen(DOSENID, NAMA_DOSEN) VALUES(1, 'Ruben');


INSERT INTO dosen(DOSENID, NAMA_DOSEN) VALUES(2, 'Doni');


--table matakuliah
CREATE TABLE matakuliah(
MATAKULIAHID INT PRIMARY KEY NOT NULL,
NAMA_MATKUL TEXT NOT NULL,
SKS INT NOT NULL
);

INSERT INTO matakuliah(MATAKULIAHID, NAMA_MATKUL, SKS) VALUES(1, 'Database', 3);

INSERT INTO matakuliah(MATAKULIAHID, NAMA_MATKUL, SKS) VALUES(2, 'Agama', 2);

--table jurusan
CREATE TABLE jurusan(
JURUSANID INT PRIMARY KEY NOT NULL,
NAMA_JURUSAN TEXT NOT NULL
);

INSERT INTO jurusan(JURUSANID, NAMA_JURUSAN) VALUES(1, 'Sistem Informatika');
INSERT INTO jurusan(JURUSANID, NAMA_JURUSAN) VALUES(2, 'Psikologi');

--table kontrakkuliah
CREATE TABLE kontrakkuliah(
KONTRAKKULIAHID INT PRIMARY KEY NOT NULL,
MAHASISWAID INT NOT NULL,
DOSENID INT NOT NULL,
MATAKULIAHID INT NOT NULL,
NILAI INT NOT NULL
);

INSERT INTO kontrakkuliah(KONTRAKKULIAHID, MAHASISWAID, DOSENID, MATAKULIAHID, NILAI) VALUES(1, 1, 1, 1, 80);
INSERT INTO kontrakkuliah(KONTRAKKULIAHID, MAHASISWAID, DOSENID, MATAKULIAHID, NILAI) VALUES(2, 2, 2, 2, 90);


SELECT mahasiswa.nama_mahasiswa, jurusan.nama_jurusan, mahasiswa.nim, matakuliah.nama_matkul, matakuliah.sks, dosen.nama_dosen, kontrakkuliah.nilai FROM kontrakkuliah
INNER JOIN mahasiswa ON kontrakkuliah.MAHASISWAID=mahasiswa.MAHASISWAID
INNER JOIN jurusan on mahasiswa.jurusanid=jurusan.jurusanid
INNER JOIN dosen ON kontrakkuliah.DOSENID=dosen.DOSENID
INNER JOIN matakuliah ON kontrakkuliah.MATAKULIAHID=matakuliah.MATAKULIAHID;
